### PR TITLE
chore: eject from CRA and upgrade/align toolchains with monorepo 

### PR DESCRIPTION
**Pull request by mcous**
This PR should be considered an RFC proposal to align the toolchain of our coding challenge more closely with our monorepo to make any future exercise changes a little easier for us to all execute. Improvements made to the experience:

- Upgrade react / react-redux to latest versions to enable hooks (if a candidate so chooses)
- HMR built in and enabled
- Redux devtools built in and enabled
- Enzyme pulled in to enable shallow-rendered snapshot testing
    - Single unit test updated to be a shallow-rendered snapshot test
- Actually hooks up a CSS Module to ease adding styling during exercise

Let me know what you think!

### CODE REVIEW

**Review by btmorr — APPROVED** [review]
🤘 this seems like a good idea

**Review by IanLondon — APPROVED** [review]
looks good

**Review by b-cooper — APPROVED** [review]
💇‍♂

**Review by Kadee80 — APPROVED** [review]
🦈

**Pull request merged**
